name: deploy to firebase

on:
  push:
    branchs:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy files to Firebase
      uses: w9jds/firebase-action@v2.0.0
      with:
          args: deploy --token $FIREBASE_TOKEN --only hosting --project sh4869-diary
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Slack Notification
      if: success()
      uses: tokorom/action-slack-incoming-webhook@master
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_HOOKS }}
      with:
        text: "[DIARY] DEPLOY COMPLETE"
        attachments: |
          [
            {
              "color": "good",
              "author_name": "${{ github.actor }}",
              "author_icon": "${{ github.event.sender.avatar_url }}",
              "fields": [
                {
                  "title": "Commit Message",
                  "value": "${{ github.event.head_commit.message }}"
                }
              ]
            }
          ]